# Spiral Matrix

In [2]:
#Example 1:

#Input:
#[
# [ 1, 2, 3 ],
# [ 4, 5, 6 ],
# [ 7, 8, 9 ]
#]
#Output: [1,2,3,6,9,8,7,4,5]

#Example 2:

#Input:
#[
#  [1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9,10,11,12]
#]
#Output: [1,2,3,4,8,12,11,10,9,5,6,7]

In [12]:
import numpy as np
def spiralOrder(matrix):
    matrix = np.array(matrix)
    print('Step 1')
    print(matrix)
    matrix = np.rot90(matrix)
    print('Step 2')
    print(matrix)
    matrix = np.rot90(matrix)
    print('Step 3')
    print(matrix)
    matrix = np.rot90(matrix)
    print('Step 4')
    print(matrix)
    rotation = 0
    while rotation <= 3:
        matrix = np.array(matrix)
        print('Step: ', rotation)

In [13]:
# right down left up
spiralOrder([[0,1,2],[3,4,5],[6,7,8]])

Step 1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Step 2
[[2 5 8]
 [1 4 7]
 [0 3 6]]
Step 3
[[8 7 6]
 [5 4 3]
 [2 1 0]]
Step 4
[[6 3 0]
 [7 4 1]
 [8 5 2]]


In [5]:
spiralOrder([1,2,3,4,5,6,7,8,9])

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9


In [ ]:
right down left up